# Generated by Django 4.2.2 on 2023-06-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
