# Generated by Django 4.2.2 on 2023-07-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_panelfile_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelfile',
            name='amount',
        ),
        migrations.AddField(
            model_name='resultfile',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
