# Generated by Django 4.2.2 on 2023-06-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_ticket_result_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='panel_file',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.panelfile'),
        ),
    ]
