# Generated by Django 4.2.2 on 2023-06-26 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='co_users',
            field=models.ManyToManyField(blank=True, related_name='co_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
