# Generated by Django 4.2.2 on 2023-06-20 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_uploadedfile_filename_alter_uploadedfile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zippedGerbers', models.FileField(upload_to='uploads/')),
                ('zippedDrills', models.FileField(upload_to='uploads/')),
                ('DRCresult', models.FileField(upload_to='uploads/')),
                ('ERCresult', models.FileField(upload_to='uploads/')),
                ('description', models.TextField(default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.TextField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
