# Generated by Django 4.2.2 on 2023-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_resultfile_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfile',
            name='pdf_file',
            field=models.FileField(default='uploads/test.pdf', upload_to='uploads/'),
        ),
    ]
