# Generated by Django 4.2.2 on 2023-07-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_panelfile_isinproduction_panelfile_isproduced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellist',
            name='error_names',
            field=models.TextField(),
        ),
    ]
