# Generated by Django 4.2.2 on 2023-07-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_panelfile_amount_resultfile_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelfile',
            name='productionStep',
            field=models.CharField(choices=[('Yet to be started', 'Yet to be started'), ('Just started', 'Just started'), ('Metalisation', 'Metalisation'), ('Almost finishied', 'Almost finishied'), ('Finished', 'Finished')], default='Yet to be started', max_length=17),
        ),
        migrations.AlterField(
            model_name='resultfile',
            name='productionStep',
            field=models.CharField(choices=[('Yet to be started', 'Yet to be started'), ('Just started', 'Just started'), ('Metalisation', 'Metalisation'), ('Almost finishied', 'Almost finishied'), ('Finished', 'Finished')], default='Yet to be started', max_length=17),
        ),
    ]
