# Generated by Django 4.2.2 on 2023-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_ticket_reopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reopen_requested',
            field=models.BooleanField(default=False),
        ),
    ]
