# Generated by Django 4.2.2 on 2023-06-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_resultfile_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultfile',
            name='selected',
        ),
    ]
