# Generated by Django 4.2.2 on 2023-06-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_resultfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='uploaded_file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadedfile'),
        ),
    ]
