# Generated by Django 4.2.2 on 2023-06-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ticket_co_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answeredByStaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.ticket'),
        ),
    ]
