# Generated by Django 4.2.2 on 2023-06-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='staff_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
