# Generated by Django 4.2.2 on 2023-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_message_answeredbystaff_alter_message_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reopened',
            field=models.BooleanField(default=False),
        ),
    ]
