kibot:
  version: 1

preflight:

  run_drc: False # Don't run the DRC 
  run_erc: False # Don't run the ERC 

outputs:

  - name: 'gerbers'
    comment: "Give 'em hell, Gerbers! - Soldier in tf2"
    type: gerber
    dir: Gerbers
    options:
      # generic layer options
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      line_width: 0.15

      # gerber options
      use_aux_axis_as_origin: false
      subtract_mask_from_silk: true
      use_protel_extensions: false
      gerber_precision: 4.5
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: false

    layers:
      - 'F.Cu'
      - 'B.Cu'
      - 'F.Paste'
      - 'B.Paste'
      - 'F.Silkscreen'
      - 'B.Silkscreen'
      - 'F.Mask'
      - 'B.Mask'
      - 'Edge.Cuts'


  - name: 'drills'
    comment: "Piece of shit drill - Payday 2"
    type: excellon
    dir: Drills