# Generated by Django 4.2.2 on 2023-07-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_modellist_panelfile_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelfile',
            name='amounts',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.modellist'),
        ),
    ]
