# Generated by Django 4.2.2 on 2023-07-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_panelfile_productionstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelfile',
            name='productionStep',
            field=models.CharField(choices=[('Yet to be started', 'Option 1'), ('Just started', 'Option 2'), ('Metalisation', 'Option 3'), ('Almost finishied', 'Option 4'), ('Finished', 'Option 5')], default='Yet to be started', max_length=17),
        ),
        migrations.AlterField(
            model_name='resultfile',
            name='productionStep',
            field=models.CharField(choices=[('Yet to be started', 'Option 1'), ('Just started', 'Option 2'), ('Metalisation', 'Option 3'), ('Almost finishied', 'Option 4'), ('Finished', 'Option 5')], default='Yet to be started', max_length=17),
        ),
    ]
