# Generated by Django 4.2.2 on 2023-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_ticket_panel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_names', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resultfile',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
