# Generated by Django 4.2.2 on 2023-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_authorizederror_alter_resultfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
