# Generated by Django 4.2.2 on 2023-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_resultfile_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
