# Generated by Django 4.2.2 on 2023-07-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_drc_error_error_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drc_error',
            name='error_names',
            field=models.TextField(default='[]'),
        ),
    ]
