# Generated by Django 4.2.2 on 2023-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_resultfile_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
