# Generated by Django 4.2.2 on 2023-07-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_panelfile_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drc_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='panelfile',
            name='Errors',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.drc_error'),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='Errors',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.drc_error'),
        ),
    ]
