# Generated by Django 4.2.2 on 2023-07-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_drc_error_panelfile_errors_resultfile_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfile',
            name='Errors',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.drc_error'),
        ),
    ]
