# Generated by Django 4.2.2 on 2023-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_panelfile_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='drc_error',
            name='error_names',
            field=models.TextField(default='[]', unique=True),
        ),
    ]
