# Generated by Django 4.2.2 on 2023-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_resultfile_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelfile',
            name='uploaded_files',
        ),
        migrations.AddField(
            model_name='panelfile',
            name='result_files',
            field=models.ManyToManyField(to='myapp.resultfile'),
        ),
    ]
