# Generated by Django 4.2.2 on 2023-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_drc_error_error_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelfile',
            name='isInProduction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelfile',
            name='isProduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelfile',
            name='isToProduce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelfile',
            name='productionStep',
            field=models.CharField(choices=[('notYet', 'Yet to be started'), ('started', 'Just started'), ('metalisation', 'Metalisation'), ('almost', 'Almost finishied'), ('finished', 'Finished')], default='notYet', max_length=12),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='isInProduction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='isProduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='isToProduce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='productionStep',
            field=models.CharField(choices=[('notYet', 'Yet to be started'), ('started', 'Just started'), ('metalisation', 'Metalisation'), ('almost', 'Almost finishied'), ('finished', 'Finished')], default='notYet', max_length=12),
        ),
    ]
